spring:
    datasource:
        url: jdbc:postgresql://51.83.131.199:5432/postgres
        username: cgrzegorz@gmail.com
        password: Karolek1marca
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect